name: Update webref
on:
  workflow_dispatch:
  schedule:
    # https://crontab.guru/#5_8_*_*_*
    - cron: "5 8 * * *"

# Conditional runs
# https://stackoverflow.com/a/61832535/2460034
jobs:
  update-webref:
    runs-on: ubuntu-latest
    outputs:
      status: steps.run-update-webref.conclusion
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '15'

      - run: npm ci
      - id: run-update-webref
        run: npm run update-webref

  rebuild:
    runs-on: ubuntu-latest
    needs: update-webref
    if: needs.check.outputs.status == 'success'
    steps:
      - run: npm run build && npm run baseline-accept
      - uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "chore(package): update webref"
          title: "chore(package): update webref"
          branch: update-webref

